### ISSUE TITLE
Fit the results to Contract_rt

### ISSUE THREAD

**Issue by thisisashukla** [thisisashukla/pgrouting#28]
Derived from [#21](https://github.com/daas-ankur-shukla/pgrouting/issues/21)

- The code for function pgr_areaContraction is generated using template for pgr_dijkstra. The input parameters in the signature had been changed, however the the output parameter in the signature remain to be changed
- [x] Edit areaContraction.sql
- [x] Edit the C file

**Comment by cvvergara** [comment]
Why did you closed this ...
as you said in gitter, you need to fix the _driver.h and the _driver.cpp files
