### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by thisisashukla** [thisisashukla/pgrouting#3]
- [x] read carefully https://summerofcode.withgoogle.com/terms/student
- [x] read carefully http://write.flossmanuals.net/gsocstudentguide/what-is-google-summer-of-code/
- [x] read careully https://wiki.osgeo.org/wiki/Google_Summer_of_Code_Recommendations_for_Students

**Comment by cvvergara** [comment]
@daas-ankur-shukla please post the link of the proposal here

**Comment by thisisashukla** [comment]
**Extension of pgRouting Contraction framework to implement Contraction Hierarchies**

https://docs.google.com/document/d/18kxlv0iZTd5y5WUiWwTaA0kty2elZT6SdLDXOCfCf68/edit
